Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.AstTools Class Reference
org.coreasm.eclipse.editors.AstTools Class Reference
This class is a helper class providing static methods and constants for navigating through the syntax tree.
Static Public Member Functions
static String findId (Node node)
Search recursively through the syntax tree until an ID node is found (pre-order)
static Node findIdNode (Node node)
Search recursively through the syntax tree until an ID node is found (pre-order)
static List< ASTNode > findChildNodes (ASTNode root, String grammarRule)
Returns a list with all direct child nodes of a certain node which are set to a specific grammar rule.
static ASTNode findFirstChildNode (ASTNode root, String grammarRule)
Returns the first direct child node of a certain node which is set to a specific grammar rule, or null if there is no such node.
static List< Node > findChildrenWithToken (ASTNode root, String token)
Returns a list with all direct child nodes of a certain node which contain a specific grammar rule.
Static Public Attributes
static final String GRAMMAR_ID = "ID"
static final String GRAMMAR_INIT = "Initialization"
static final String GRAMMAR_RULE = "RuleDeclaration"
static final String PARSER_USE = "UseClause"
static final String PARSER_HEADER = "Header"
static final String PARSER_RULE = GRAMMAR_RULE
static final String PLUGIN_KERNEL = "Kernel"
Detailed Description
This class is a helper class providing static methods and constants for navigating through the syntax tree.
Author
Markus Müller
Definition at line 14 of file AstTools.java.
Member Function Documentation
static String org.coreasm.eclipse.editors.AstTools.findId (Node node) static
Search recursively through the syntax tree until an ID node is found (pre-order)
Parameters
node The node where the search is started (the root of the recursion)
Returns
The ID of the first ID node being found.
Definition at line 34 of file AstTools.java.
References org.coreasm.eclipse.editors.AstTools.findIdNode().
Referenced by org.coreasm.eclipse.editors.errors.InitErrorRecognizer.getInitRuleDefinition().
static Node org.coreasm.eclipse.editors.AstTools.findIdNode (Node node) static
Search recursively through the syntax tree until an ID node is found (pre-order)
Parameters
node The node where the search is started (the root of the recursion)
Returns
The first ID node being found.
Definition at line 46 of file AstTools.java.
Referenced by org.coreasm.eclipse.editors.AstTools.findId().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/AstTools.java