Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.wizards.ASMWizardPage Class Reference
org.coreasm.eclipse.wizards.ASMWizardPage Class Reference
The "New" wizard page allows setting the container for the new file as well as the file name.
Public Member Functions
ASMWizardPage (ISelection selection)
Constructor for SampleNewWizardPage.
void createControl (Composite parent)
String getContainerName ()
String getFileName ()
Private Member Functions
void initialize ()
Tests if the current workbench selection is a suitable container to use.
void handleBrowse ()
Uses the standard container selection dialog to choose the new value for the container field.
void dialogChanged ()
Ensures that both text fields are set.
void updateStatus (String message)
Private Attributes
Text containerText
Text fileText
ISelection selection
Detailed Description
The "New" wizard page allows setting the container for the new file as well as the file name.
The page will only accept file name without the extension OR with the extension that matches the expected ones (casm or coreasm).
Definition at line 33 of file ASMWizardPage.java.
Constructor & Destructor Documentation
org.coreasm.eclipse.wizards.ASMWizardPage.ASMWizardPage (ISelection selection)
Constructor for SampleNewWizardPage.
Parameters
pageName
Definition at line 45 of file ASMWizardPage.java.
Member Function Documentation
void org.coreasm.eclipse.wizards.ASMWizardPage.createControl (Composite parent)
See Also
IDialogPage::createControl(Composite)
Definition at line 61 of file ASMWizardPage.java.
References org.coreasm.eclipse.wizards.ASMWizardPage.dialogChanged(), org.coreasm.eclipse.wizards.ASMWizardPage.handleBrowse(), and org.coreasm.eclipse.wizards.ASMWizardPage.initialize().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/wizards/ASMWizardPage.java