Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.wizards.ASMNewWizard Class Reference
org.coreasm.eclipse.wizards.ASMNewWizard Class Reference
This is a sample new wizard.
Public Member Functions
ASMNewWizard ()
Constructor for ASMNewWizard.
void addPages ()
Adding the page to the wizard.
boolean performFinish ()
This method is called when 'Finish' button is pressed in the wizard.
void init (IWorkbench workbench, IStructuredSelection selection)
We will accept the selection in the workbench to see if we can initialize from it.
Private Member Functions
void doFinish (String containerName, String fileName, IProgressMonitor monitor) throws CoreException
The worker method.
InputStream openContentStream (String fileName)
We will initialize file contents with a sample text.
void throwCoreException (String message) throws CoreException
Private Attributes
ASMWizardPage page
ISelection selection
Detailed Description
This is a sample new wizard.
Its role is to create a new file resource in the provided container. If the container resource (a folder or a project) is selected in the workspace when the wizard is opened, it will accept it as the target container. The wizard creates one file with the extension "casm" or "coreasm". If a sample multi-page editor (also available as a template) is registered for the same extension, it will be able to open it.
Definition at line 42 of file ASMNewWizard.java.
Member Function Documentation
void org.coreasm.eclipse.wizards.ASMNewWizard.doFinish (String containerName, String fileName, IProgressMonitor monitor) throws CoreException private
The worker method.
It will find the container, create the file if missing or just replace its contents, and open the editor on the newly created file.
Definition at line 103 of file ASMNewWizard.java.
References org.coreasm.eclipse.wizards.ASMNewWizard.openContentStream().
Referenced by org.coreasm.eclipse.wizards.ASMNewWizard.performFinish().
void org.coreasm.eclipse.wizards.ASMNewWizard.init (IWorkbench workbench, IStructuredSelection selection)
We will accept the selection in the workbench to see if we can initialize from it.
See Also
IWorkbenchWizard::init(IWorkbench, IStructuredSelection)
Definition at line 177 of file ASMNewWizard.java.
InputStream org.coreasm.eclipse.wizards.ASMNewWizard.openContentStream (String fileName) private
We will initialize file contents with a sample text.
Parameters
containerName
Definition at line 149 of file ASMNewWizard.java.
Referenced by org.coreasm.eclipse.wizards.ASMNewWizard.doFinish().
boolean org.coreasm.eclipse.wizards.ASMNewWizard.performFinish ()
This method is called when 'Finish' button is pressed in the wizard.
We will create an operation and run it using wizard as execution context.
Definition at line 70 of file ASMNewWizard.java.
References org.coreasm.eclipse.wizards.ASMNewWizard.doFinish().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/wizards/ASMNewWizard.java