Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.ASMDocument Class Reference
org.coreasm.eclipse.editors.ASMDocument Class Reference
The ASMDocument class represents a CoreASM specification as a document of an Eclipse CoreASM editor.
Classes
class HeaderElement
This class represents an header element of the syntax tree.
Public Member Functions
boolean isIncludedSpecification ()
This method returns if a specification is a module or not.
void resetInclusionState ()
This method causes the document to "forget" if it is a "CoreASM" or a "CoreModule" specification, so this will be rechecked the next time the method isIncludedSpecification() is called.
Node getRootnode ()
int getNodePosition (Node node)
Returns the position of the specified Node in this document.
int getCharPosition (CharacterPosition charPos, Specification spec)
Returns the position of the specified CharacterPosition in this document.
ASTNode getIDnodeAt (int offset)
List< ASTNode > getASTNodesOnLine (int line)
Returns a list of nodes in the specified line.
List< ASTNode > getASTNodesOnLineOfOffset (int offset) throws BadLocationException
Returns a list of nodes in the line of the specified offset.
int getLineOfNode (ASTNode node) throws BadLocationException
Returns the line number of the specified node.
void setControlAPI (ControlAPI capi)
int getUpdatedOffset (int oldOffset)
Returns the current offset of a specific header element, specified by its original offset at the last successful parsing.
Static Public Member Functions
static int calculateLength (Node node)
Private Member Functions
void checkIfSpecificationIsIncluded ()
This method checks if the CoreASM specification which is represented by the document is a normal specification (starting with the keyword "CoreASM") or if it is intended to be included in other specifications (starting with the keyword "CoreModule").
String getContent (int offset)
Returns the content type of the partition at a certain offset.
Private Attributes
Node rootnode = null
References the rootnote of the syntax tree of the specifications, contains null if the specification haven't been parsed before or if the last parsing caused an error.
List< HeaderElement > headerElements
This list contains all syntax elements of the uppermost level below the rootnode.
Boolean isIncluded = null
This flag stores if a specification is a full specification (beginning with "CoreASM") or if it is a module (beginning with "CoreModule").
ControlAPI capi
synchronized void addPosition (String category, Position position) throws BadLocationException, BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized void addPositionCategory (String category)
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized boolean containsPosition (String category, int offset, int length)
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized boolean containsPositionCategory (String category)
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized int computeIndexInCategory (String category, int offset) throws BadLocationException, BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized Position[] getPositions (String category) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized String[] getPositionCategories ()
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized void removePosition (Position position)
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized void removePosition (String category, Position position) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized void removePositionCategory (String category) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized void addPosition (Position position) throws BadLocationException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized Position[] getPositions (String category, int offset, int length, boolean canStartBefore, boolean canEndAfter) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized Map getDocumentManagedPositions ()
Avoid ConcurrentModificationExceptions in case of document accesses.
synchronized void completeInitialization ()
Avoid ConcurrentModificationExceptions in case of document accesses.
Detailed Description
The ASMDocument class represents a CoreASM specification as a document of an Eclipse CoreASM editor.
Author
Markus Müller, Michael Stegmaier, Marcel Dausend
Definition at line 28 of file ASMDocument.java.
Member Function Documentation
synchronized void org.coreasm.eclipse.editors.ASMDocument.addPosition (String category, Position position) throws BadLocationException, BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 414 of file ASMDocument.java.
synchronized void org.coreasm.eclipse.editors.ASMDocument.addPosition (Position position) throws BadLocationException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 486 of file ASMDocument.java.
synchronized void org.coreasm.eclipse.editors.ASMDocument.addPositionCategory (String category)
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 421 of file ASMDocument.java.
void org.coreasm.eclipse.editors.ASMDocument.checkIfSpecificationIsIncluded () private
This method checks if the CoreASM specification which is represented by the document is a normal specification (starting with the keyword "CoreASM") or if it is intended to be included in other specifications (starting with the keyword "CoreModule").
The result of the method is stored in the variable isIncluded.
Definition at line 77 of file ASMDocument.java.
References org.coreasm.eclipse.editors.ASMDocument.getContent(), and org.coreasm.eclipse.editors.ASMDocument.isIncluded.
Referenced by org.coreasm.eclipse.editors.ASMDocument.isIncludedSpecification().
synchronized void org.coreasm.eclipse.editors.ASMDocument.completeInitialization () protected
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 480 of file ASMDocument.java.
synchronized int org.coreasm.eclipse.editors.ASMDocument.computeIndexInCategory (String category, int offset) throws BadLocationException, BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 440 of file ASMDocument.java.
synchronized boolean org.coreasm.eclipse.editors.ASMDocument.containsPosition (String category, int offset, int length)
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 427 of file ASMDocument.java.
synchronized boolean org.coreasm.eclipse.editors.ASMDocument.containsPositionCategory (String category)
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 434 of file ASMDocument.java.
List<ASTNode> org.coreasm.eclipse.editors.ASMDocument.getASTNodesOnLine (int line)
Returns a list of nodes in the specified line.
Parameters
line Line to return nodes of
Returns
List of nodes in the specified line
Definition at line 232 of file ASMDocument.java.
References org.coreasm.eclipse.editors.ASMDocument.getNodePosition().
Referenced by org.coreasm.eclipse.editors.ASMDocument.getASTNodesOnLineOfOffset().
List<ASTNode> org.coreasm.eclipse.editors.ASMDocument.getASTNodesOnLineOfOffset (int offset) throws BadLocationException
Returns a list of nodes in the line of the specified offset.
Parameters
offset Offset in the line of which the nodes should be returned
Returns
List of nodes in the line of the specified offset
Definition at line 260 of file ASMDocument.java.
References org.coreasm.eclipse.editors.ASMDocument.getASTNodesOnLine().
int org.coreasm.eclipse.editors.ASMDocument.getCharPosition (CharacterPosition charPos, Specification spec)
Returns the position of the specified CharacterPosition in this document.
Parameters
charPos CharacterPosition to return position of
spec Specification of the CharacterPosition
Returns
position of the specified CharacterPosition
Definition at line 194 of file ASMDocument.java.
String org.coreasm.eclipse.editors.ASMDocument.getContent (int offset) private
Returns the content type of the partition at a certain offset.
Parameters
offset The character for which the content type shouls be returned
Returns
The tag of the content type, or "" if there was an exception.
Definition at line 365 of file ASMDocument.java.
Referenced by org.coreasm.eclipse.editors.ASMDocument.checkIfSpecificationIsIncluded().
synchronized Map org.coreasm.eclipse.editors.ASMDocument.getDocumentManagedPositions () protected
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 408 of file ASMDocument.java.
int org.coreasm.eclipse.editors.ASMDocument.getLineOfNode (ASTNode node) throws BadLocationException
Returns the line number of the specified node.
Parameters
node Node to return line number of
Returns
the line number of the specified node
Exceptions
BadLocationException
Definition at line 272 of file ASMDocument.java.
References org.coreasm.eclipse.editors.ASMDocument.getNodePosition().
int org.coreasm.eclipse.editors.ASMDocument.getNodePosition (Node node)
Returns the position of the specified Node in this document.
Parameters
node Node to return position of
Returns
position of the specified node
Definition at line 150 of file ASMDocument.java.
Referenced by org.coreasm.eclipse.editors.ASMDocument.getASTNodesOnLine(), and org.coreasm.eclipse.editors.ASMDocument.getLineOfNode().
synchronized String [] org.coreasm.eclipse.editors.ASMDocument.getPositionCategories ()
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 454 of file ASMDocument.java.
synchronized Position [] org.coreasm.eclipse.editors.ASMDocument.getPositions (String category) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 447 of file ASMDocument.java.
synchronized Position [] org.coreasm.eclipse.editors.ASMDocument.getPositions (String category, int offset, int length, boolean canStartBefore, boolean canEndAfter) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 493 of file ASMDocument.java.
int org.coreasm.eclipse.editors.ASMDocument.getUpdatedOffset (int oldOffset)
Returns the current offset of a specific header element, specified by its original offset at the last successful parsing.
Parameters
oldOffset The original offset of a header element from the last successful parsing.
Returns
The current offset of this header element, or oldOffset if there was no header element with that offset.
Definition at line 350 of file ASMDocument.java.
boolean org.coreasm.eclipse.editors.ASMDocument.isIncludedSpecification ()
This method returns if a specification is a module or not.
Returns
true if it is a module, false otherwise.
Definition at line 63 of file ASMDocument.java.
References org.coreasm.eclipse.editors.ASMDocument.checkIfSpecificationIsIncluded(), and org.coreasm.eclipse.editors.ASMDocument.isIncluded.
synchronized void org.coreasm.eclipse.editors.ASMDocument.removePosition (Position position)
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 460 of file ASMDocument.java.
synchronized void org.coreasm.eclipse.editors.ASMDocument.removePosition (String category, Position position) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 466 of file ASMDocument.java.
synchronized void org.coreasm.eclipse.editors.ASMDocument.removePositionCategory (String category) throws BadPositionCategoryException
Avoid ConcurrentModificationExceptions in case of document accesses.
The method has to be synchronized due to a bug in Eclipse.
Definition at line 473 of file ASMDocument.java.
Member Data Documentation
List<HeaderElement> org.coreasm.eclipse.editors.ASMDocument.headerElements private
This list contains all syntax elements of the uppermost level below the rootnode.
The list is remembered if the last parsing caused an error.
Definition at line 42 of file ASMDocument.java.
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/ASMDocument.java