Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.outlining.ParsedContentProvider Class Reference
org.coreasm.eclipse.editors.outlining.ParsedContentProvider Class Reference
Content provider for ParsedOutlinePage.
Classes
enum DisplayModeOrder
enum DisplayModeStructure
Public Member Functions
ParsedContentProvider (IDocumentProvider documentProvider, ASMEditor editor)
void addRootNode (RootOutlineTreeNode rootNode)
void removeRootNode (RootOutlineTreeNode rootNode)
void clearExternRootList ()
void setDisplayMode (DisplayModeStructure structure, DisplayModeOrder order)
void setDisplayMode (DisplayModeStructure structure)
void setDisplayMode (DisplayModeOrder order)
void dispose ()
void inputChanged (Viewer viewer, Object oldInput, Object newInput)
This method is called if the input of the ASMEditor this content provider belongs to has changed.
Object[] getElements (Object inputElement)
This method returns the root element of the outline tree.
Object[] getChildren (Object parentElement)
Object getParent (Object element)
boolean hasChildren (Object element)
Private Member Functions
void appendChild (Node childNode, RootOutlineTreeNode oRootNode)
Private Attributes
IDocumentProvider documentProvider
IPositionUpdater positionUpdater = new DefaultPositionUpdater(AST_POSITIONS)
ASMEditor editor
ASMParser parser
DisplayModeStructure outlineStructure
DisplayModeOrder outlineOrder
ParsedOutlinePage outlinePage
ArrayList< OutlineTreeNode > lastRootList
ArrayList< OutlineTreeNode > externRootList
Static Private Attributes
static final String AST_POSITIONS = "__ast_position"
Detailed Description
Content provider for ParsedOutlinePage.
Author
Markus Müller, Tobias Seyfang
Definition at line 31 of file ParsedContentProvider.java.
Member Function Documentation
void org.coreasm.eclipse.editors.outlining.ParsedContentProvider.addRootNode (RootOutlineTreeNode rootNode)
Parameters
rootNode Root node from an extern source (plugin)
Definition at line 71 of file ParsedContentProvider.java.
void org.coreasm.eclipse.editors.outlining.ParsedContentProvider.appendChild (Node childNode, RootOutlineTreeNode oRootNode) private
Parameters
childNode
oRootNode Root node which to
Appends a child to oRootNode Extracts the childNode description depending on the type (e.g GRAMMAR_RULE)
Definition at line 206 of file ParsedContentProvider.java.
References org.coreasm.eclipse.editors.ASMEditor.getInputFile().
Referenced by org.coreasm.eclipse.editors.outlining.ParsedContentProvider.getElements().
Object [] org.coreasm.eclipse.editors.outlining.ParsedContentProvider.getChildren (Object parentElement)
Parameters
parentElement The parent for which the children are returned, must be an instance of class OutlineTreeNode.
Gets the child nodes for the given OutlineTreeNode.
Returns all nodes when FLAT is set. Else return group nodes if the parentElement is a RootOutlineTreeNode or return children of a group node
Definition at line 267 of file ParsedContentProvider.java.
Object [] org.coreasm.eclipse.editors.outlining.ParsedContentProvider.getElements (Object inputElement)
This method returns the root element of the outline tree.
If there is no tree to be displayed the DUMMY node is displayed. Otherwise an OutlineTreeNode of type ROOT is created as the root.
Definition at line 154 of file ParsedContentProvider.java.
References org.coreasm.eclipse.editors.outlining.ParsedContentProvider.appendChild().
void org.coreasm.eclipse.editors.outlining.ParsedContentProvider.inputChanged (Viewer viewer, Object oldInput, Object newInput)
This method is called if the input of the ASMEditor this content provider belongs to has changed.
If this happens, the ContentProvider must remove its PositionUpdater from the old input and add it to the new input. The PositionUpdater watches the input of the ASMEditor for changes and keeps the positions the outline node are rerferring to up to date.
Todo:
why does this exception occur?
Definition at line 121 of file ParsedContentProvider.java.
void org.coreasm.eclipse.editors.outlining.ParsedContentProvider.removeRootNode (RootOutlineTreeNode rootNode)
Parameters
rootNode Root node from an extern source (plugin)
Definition at line 78 of file ParsedContentProvider.java.
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/outlining/ParsedContentProvider.java