Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.IconManager Class Reference
org.coreasm.eclipse.editors.IconManager Class Reference
Static helper class for loading image files.
Static Public Member Functions
static synchronized ImageDescriptor getDescriptor (String filename)
Returns the ImageDescriptor object of an image given by its filename.
static synchronized Image getIcon (String filename)
Returns the Image object of an image given by its filename.
static synchronized ImageDescriptor getDescriptor (URL filename)
static synchronized Image getIcon (URL filename)
Static Private Attributes
static Map< String,
ImageDescriptor > DESCR_MAP
static Map< String, Image > IMAGE_MAP
static Map< URL, ImageDescriptor > DESCR_MAP_URL
static Map< URL, Image > IMAGE_MAP_URL
Detailed Description
Static helper class for loading image files.
The class stores each images it has loaded into a Map, from which an image is reused if it is requested a second time.
Added URL so that we can create images from plugin icons
Author
Markus Müller, Tobias
Definition at line 19 of file IconManager.java.
Member Function Documentation
static synchronized ImageDescriptor org.coreasm.eclipse.editors.IconManager.getDescriptor (String filename) static
Returns the ImageDescriptor object of an image given by its filename.
Parameters
filename
Returns
Definition at line 38 of file IconManager.java.
Referenced by org.coreasm.eclipse.editors.IconManager.getIcon().
static synchronized ImageDescriptor org.coreasm.eclipse.editors.IconManager.getDescriptor (URL filename) static
Parameters
filename The URL of the icon
Returns
Returns the ImageDescriptor object of an image given by its filename.
Definition at line 73 of file IconManager.java.
static synchronized Image org.coreasm.eclipse.editors.IconManager.getIcon (String filename) static
Returns the Image object of an image given by its filename.
Parameters
filename
Returns
Definition at line 54 of file IconManager.java.
References org.coreasm.eclipse.editors.IconManager.getDescriptor().
static synchronized Image org.coreasm.eclipse.editors.IconManager.getIcon (URL filename) static
Parameters
filename The URL of the icon
Returns
Returns the ImageDescriptor object of an image given by its filename.
Definition at line 90 of file IconManager.java.
References org.coreasm.eclipse.editors.IconManager.getDescriptor().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/IconManager.java