Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.launch.SourceTabComposite2 Class Reference
org.coreasm.eclipse.launch.SourceTabComposite2 Class Reference
Public Member Functions
SourceTabComposite2 (Composite parent, int style)
Button getDumpState ()
Button getDumpUpdates ()
Combo getLogLevel ()
Spinner getMaxSteps ()
Text getProject ()
Text getSpec ()
Button getStopOnEmptyUpdates ()
Button getStopOnErrors ()
Button getStopOnFailedUpdates ()
Button getStopOnMaxSteps ()
Button getStopOnStableUpdates ()
Button getStopOnEmptyActiveAgents ()
Button getBrowseProjectButton ()
Button getBrowseSpecButton ()
Button getDumpFinal ()
Button getMarkSteps ()
Button getPrintAgents ()
Static Public Member Functions
static void main (String[] args)
Private Member Functions
void createGroup ()
This method initializes group.
void createGroup1 ()
This method initializes group1.
void createGroup2 ()
This method initializes group2.
void createComposite ()
This method initializes composite.
void createCombo ()
This method initializes combo.
void createComposite1 ()
This method initializes composite1.
void initialize ()
Private Attributes
Group group = null
Group group1 = null
Group group2 = null
Label label = null
Text project = null
Button browseProjectButton = null
Label label1 = null
Text spec = null
Button browseSpecButton = null
Button stopOnErrors = null
Label label2 = null
Button stopOnFailedUpdates = null
Label label3 = null
Button stopOnEmptyUpdates = null
Label label4 = null
Button stopOnStableUpdates = null
Label label5 = null
Button stopOnEmptyActiveAgents = null
Label label5_6 = null
Button stopOnMaxSteps = null
Label label6 = null
Spinner maxSteps = null
Composite composite = null
Label label8 = null
Combo logLevel = null
Composite composite1 = null
Button dumpUpdates = null
Label label7 = null
Button dumpState = null
Label label9 = null
Button dumpFinal = null
Label label10 = null
Button markSteps = null
Label label11 = null
Button printAgents = null
Label label12 = null
Detailed Description
Definition at line 19 of file SourceTabComposite2.java.
Member Function Documentation
void org.coreasm.eclipse.launch.SourceTabComposite2.createCombo () private
This method initializes combo.
Definition at line 191 of file SourceTabComposite2.java.
Referenced by org.coreasm.eclipse.launch.SourceTabComposite2.createComposite().
void org.coreasm.eclipse.launch.SourceTabComposite2.createComposite () private
This method initializes composite.
Definition at line 176 of file SourceTabComposite2.java.
References org.coreasm.eclipse.launch.SourceTabComposite2.createCombo().
Referenced by org.coreasm.eclipse.launch.SourceTabComposite2.createGroup2().
void org.coreasm.eclipse.launch.SourceTabComposite2.createComposite1 () private
This method initializes composite1.
Definition at line 203 of file SourceTabComposite2.java.
Referenced by org.coreasm.eclipse.launch.SourceTabComposite2.createGroup2().
void org.coreasm.eclipse.launch.SourceTabComposite2.createGroup () private
This method initializes group.
Definition at line 62 of file SourceTabComposite2.java.
void org.coreasm.eclipse.launch.SourceTabComposite2.createGroup1 () private
This method initializes group1.
Definition at line 98 of file SourceTabComposite2.java.
void org.coreasm.eclipse.launch.SourceTabComposite2.createGroup2 () private
This method initializes group2.
Definition at line 158 of file SourceTabComposite2.java.
References org.coreasm.eclipse.launch.SourceTabComposite2.createComposite(), and org.coreasm.eclipse.launch.SourceTabComposite2.createComposite1().
Button org.coreasm.eclipse.launch.SourceTabComposite2.getBrowseProjectButton ()
Returns
Returns the browseProjectButton.
Definition at line 346 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getBrowseSpecButton ()
Returns
Returns the browseSpecButton.
Definition at line 353 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getDumpFinal ()
Returns
Returns the dumpFinal.
Definition at line 360 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getDumpState ()
Returns
Returns the dumpState.
Definition at line 265 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getDumpUpdates ()
Returns
Returns the dumpUpdates.
Definition at line 272 of file SourceTabComposite2.java.
Combo org.coreasm.eclipse.launch.SourceTabComposite2.getLogLevel ()
Returns
Returns the logLevel.
Definition at line 279 of file SourceTabComposite2.java.
Referenced by org.coreasm.eclipse.launch.SourceTab.initializeFrom().
Button org.coreasm.eclipse.launch.SourceTabComposite2.getMarkSteps ()
Returns
mark steps check box
Definition at line 367 of file SourceTabComposite2.java.
Spinner org.coreasm.eclipse.launch.SourceTabComposite2.getMaxSteps ()
Returns
Returns the maxSteps.
Definition at line 286 of file SourceTabComposite2.java.
Text org.coreasm.eclipse.launch.SourceTabComposite2.getProject ()
Returns
Returns the project.
Definition at line 293 of file SourceTabComposite2.java.
Text org.coreasm.eclipse.launch.SourceTabComposite2.getSpec ()
Returns
Returns the spec.
Definition at line 300 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getStopOnEmptyUpdates ()
Returns
Returns the stopOnEmptyUpdates.
Definition at line 307 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getStopOnErrors ()
Returns
Returns the stopOnErrors.
Definition at line 314 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getStopOnFailedUpdates ()
Returns
Returns the stopOnFailedUpdates.
Definition at line 321 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getStopOnMaxSteps ()
Returns
Returns the stopOnMaxSteps.
Definition at line 328 of file SourceTabComposite2.java.
Button org.coreasm.eclipse.launch.SourceTabComposite2.getStopOnStableUpdates ()
Returns
Returns the stopOnStableUpdates.
Definition at line 335 of file SourceTabComposite2.java.
static void org.coreasm.eclipse.launch.SourceTabComposite2.main (String[] args) static
Parameters
args
Definition at line 228 of file SourceTabComposite2.java.
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/launch/SourceTabComposite2.java