Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.engine.debugger.EngineDebugger Class Reference
org.coreasm.eclipse.engine.debugger.EngineDebugger Class Reference
This is the main class of the the debugger.
Public Member Functions
synchronized void stop ()
synchronized void pause ()
synchronized void resume ()
synchronized void setStepping (boolean shouldStep)
Sets the stepping mode of the debugger.
synchronized boolean isStepping ()
Returns whether the debugger is stepping.
synchronized void stepOver ()
Executes a single engine step.
synchronized void stepInto ()
Executes a single interpreter step.
synchronized void stepReturn ()
Executes the rest of the engine step.
ASMStorage[] getStates ()
Returns the stack of states.
String setValue (String functionName, String expression)
Sets the value of the given function.
Element evaluateExpression (String expression, ASMStorage storage) throws ParserException, InterpreterException
Set< ASMUpdate > getUpdates ()
Returns the current updates as a set of ASMUpdate.
int getStep ()
Returns the current step.
synchronized void updateStatus (EngineDriverStatus status)
void dropToState (ASMStorage stateToDropTo)
Restores the given state.
void update (EngineEvent event)
void setDebugTarget (ASMDebugTarget debugTarget)
Sets the debug target.
String getSpecPath ()
Returns the path of the running specification.
void updateState (ASTNode pos)
Updates/Creates the current state.
void beforeNodeEvaluation (ASTNode pos)
void afterNodeEvaluation (ASTNode pos)
void onRuleCall (RuleElement rule, List< ASTNode > args, ASTNode pos, Element agent)
void onRuleExit (RuleElement rule, List< ASTNode > args, ASTNode pos, Element agent)
void initProgramExecution (Element agent, RuleElement program)
Public Member Functions inherited from org.coreasm.eclipse.engine.driver.EngineDriver
synchronized void updateStatus (EngineDriverStatus status)
EngineDriverStatus getStatus ()
void setDefaultConfig ()
void setConfig (ILaunchConfiguration config)
void finalize ()
void dolaunch (String abspathname)
synchronized void stop ()
synchronized void pause ()
synchronized void resume ()
void run ()
synchronized Specification getSpec (String text, boolean loadPlugins)
void update (EngineEvent event)
int getMaxsteps ()
void setMaxsteps (int maxsteps)
boolean isStopOnEmptyUpdates ()
void setStopOnEmptyUpdates (boolean stopOnEmptyUpdates)
boolean isStopOnError ()
void setStopOnError (boolean stopOnError)
boolean isStopOnFailedUpdates ()
void setStopOnFailedUpdates (boolean stopOnFailedUpdates)
boolean isStopOnEmptyActiveAgents ()
void setStopOnEmptyActiveAgents (boolean b)
boolean isStopOnStableUpdates ()
void setStopOnStableUpdates (boolean stopOnStableUpdates)
boolean isStopOnStepsLimit ()
void setStopOnStepsLimit (boolean stopOnStepsLimit)
int getStepsLimit ()
void setStepsLimit (int stepsLimit)
CoreASMError getLastError ()
String getStepFailedMsg ()
boolean isUpdateFailed ()
boolean isDumpFinal ()
void setDumpFinal (boolean dumpFinal)
Static Public Member Functions
static EngineDebugger getRunningInstance ()
Returns the running instance of the debugger.
static void newLaunch (String abspathname, ILaunchConfiguration config) throws CoreException
Creates a new launch for the given path and configuration.
Static Public Member Functions inherited from org.coreasm.eclipse.engine.driver.EngineDriver
static synchronized EngineDriver getSyntaxInstance ()
static EngineDriver getRunningInstance ()
static synchronized void addAction (EngineDriverAction action)
static void newLaunch (String abspathname) throws CoreException
static void newLaunch (String abspathname, ILaunchConfiguration config) throws CoreException
Protected Member Functions
EngineDebugger (boolean isSyntaxEngine)
void preExecutionCallback ()
void postExecutionCallback ()
void handleError ()
Protected Member Functions inherited from org.coreasm.eclipse.engine.driver.EngineDriver
EngineDriver (boolean isSyntaxEngine)
void preExecutionCallback ()
void postExecutionCallback ()
void handleError ()
Private Member Functions
void waitForStep (ASTNode pos)
Pauses the execution until the user resumes it.
void onBreakpointHit (ASTNode pos)
This method is called whenever a breakpoint is hit.
boolean isUnvisited (ASTNode pos)
Returns whether pos has been visited before or not.
boolean isWatchpointHit (FunctionRuleTermNode frNode)
Returns whether frNode hits a breakpoint.
boolean isLineBreakpointHit ()
Private Attributes
ControlAPI capi = (ControlAPI)engine
WatchExpressionAPI wapi = new WatchExpressionAPI(capi)
Stack< ASMStorage > states = new Stack<ASMStorage>()
ASMDebugTarget debugTarget
String sourceName
String specPath
Element currentAgent
int lineNumber
ASTNode stepOverPos
ASTNode stepReturnPos
ASTNode prevPos
Map< ASTNode, String > ruleArgs
Set< ASMUpdate > updates = new HashSet<ASMUpdate>()
IBreakpoint prevWatchpoint
boolean stepSucceeded = false
volatile boolean shouldStep = false
volatile boolean shouldStepReturn = false
volatile boolean shouldStepOver = false
volatile boolean shouldStepInto = false
Additional Inherited Members
Protected Attributes inherited from org.coreasm.eclipse.engine.driver.EngineDriver
CoreASMEngine engine
CoreASMError lastError
Static Protected Attributes inherited from org.coreasm.eclipse.engine.driver.EngineDriver
static EngineDriver runningInstance =null
Detailed Description
This is the main class of the the debugger.
It controls the engine and provides access to it's state.
Author
Michael Stegmaier
Definition at line 67 of file EngineDebugger.java.
Member Function Documentation
void org.coreasm.eclipse.engine.debugger.EngineDebugger.dropToState (ASMStorage stateToDropTo)
Restores the given state.
Parameters
stateToDropTo State to drop to
Definition at line 305 of file EngineDebugger.java.
References org.coreasm.eclipse.engine.debugger.EngineDebugger.setValue().
static EngineDebugger org.coreasm.eclipse.engine.debugger.EngineDebugger.getRunningInstance () static
Returns the running instance of the debugger.
Returns
the running instance of the debugger
Definition at line 98 of file EngineDebugger.java.
String org.coreasm.eclipse.engine.debugger.EngineDebugger.getSpecPath ()
Returns the path of the running specification.
Returns
the path of the running specification
Definition at line 369 of file EngineDebugger.java.
ASMStorage [] org.coreasm.eclipse.engine.debugger.EngineDebugger.getStates ()
Returns the stack of states.
Returns
the stack of states
Definition at line 176 of file EngineDebugger.java.
int org.coreasm.eclipse.engine.debugger.EngineDebugger.getStep ()
Returns the current step.
Returns
the current step
Definition at line 235 of file EngineDebugger.java.
Referenced by org.coreasm.eclipse.engine.debugger.EngineDebugger.updateState().
Set<ASMUpdate> org.coreasm.eclipse.engine.debugger.EngineDebugger.getUpdates ()
Returns the current updates as a set of ASMUpdate.
Returns
the current updates as a set of ASMUpdate
Definition at line 227 of file EngineDebugger.java.
Referenced by org.coreasm.eclipse.engine.debugger.EngineDebugger.updateState().
synchronized boolean org.coreasm.eclipse.engine.debugger.EngineDebugger.isStepping ()
Returns whether the debugger is stepping.
Returns
whether the debugger is stepping
Definition at line 134 of file EngineDebugger.java.
boolean org.coreasm.eclipse.engine.debugger.EngineDebugger.isUnvisited (ASTNode pos) private
Returns whether pos has been visited before or not.
Parameters
pos ASTNode to test
Returns
whether pos has been visited before or not
Definition at line 467 of file EngineDebugger.java.
boolean org.coreasm.eclipse.engine.debugger.EngineDebugger.isWatchpointHit (FunctionRuleTermNode frNode) private
Returns whether frNode hits a breakpoint.
Parameters
frNode ASTNode to test
Returns
whether frNode hits a breakpoint
Definition at line 485 of file EngineDebugger.java.
static void org.coreasm.eclipse.engine.debugger.EngineDebugger.newLaunch (String abspathname, ILaunchConfiguration config) throws CoreException static
Creates a new launch for the given path and configuration.
Parameters
abspathname path of the launch to create
config configuration for the launch to create
Exceptions
CoreException when another specification is currently running
Definition at line 288 of file EngineDebugger.java.
void org.coreasm.eclipse.engine.debugger.EngineDebugger.onBreakpointHit (ASTNode pos) private
This method is called whenever a breakpoint is hit.
Parameters
pos the node that the breakpoint was attached to
Definition at line 401 of file EngineDebugger.java.
References org.coreasm.eclipse.engine.debugger.EngineDebugger.setStepping(), org.coreasm.eclipse.engine.debugger.EngineDebugger.updateState(), and org.coreasm.eclipse.engine.debugger.EngineDebugger.waitForStep().
void org.coreasm.eclipse.engine.debugger.EngineDebugger.setDebugTarget (ASMDebugTarget debugTarget)
Sets the debug target.
Parameters
debugTarget debug target to set
Definition at line 361 of file EngineDebugger.java.
synchronized void org.coreasm.eclipse.engine.debugger.EngineDebugger.setStepping (boolean shouldStep)
Sets the stepping mode of the debugger.
Parameters
shouldStep value to set the stepping mode to
Definition at line 126 of file EngineDebugger.java.
Referenced by org.coreasm.eclipse.engine.debugger.EngineDebugger.onBreakpointHit().
String org.coreasm.eclipse.engine.debugger.EngineDebugger.setValue (String functionName, String expression)
Sets the value of the given function.
Parameters
functionName name of the function of which the value should be changed
expression a string representation of the value
Returns
the value that the function actually got after setting
Definition at line 188 of file EngineDebugger.java.
Referenced by org.coreasm.eclipse.engine.debugger.EngineDebugger.dropToState().
void org.coreasm.eclipse.engine.debugger.EngineDebugger.updateState (ASTNode pos)
Updates/Creates the current state.
Parameters
pos Current position of the state
Definition at line 416 of file EngineDebugger.java.
References org.coreasm.eclipse.engine.debugger.EngineDebugger.getStep(), org.coreasm.eclipse.engine.debugger.EngineDebugger.getUpdates(), and org.coreasm.eclipse.engine.driver.EngineDriver.run().
Referenced by org.coreasm.eclipse.engine.debugger.EngineDebugger.onBreakpointHit().
void org.coreasm.eclipse.engine.debugger.EngineDebugger.waitForStep (ASTNode pos) private
Pauses the execution until the user resumes it.
Parameters
pos the current node
Definition at line 377 of file EngineDebugger.java.
Referenced by org.coreasm.eclipse.engine.debugger.EngineDebugger.onBreakpointHit().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/engine/debugger/EngineDebugger.java