Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.outlining.AbstractContentPage Class Reference
org.coreasm.eclipse.editors.outlining.AbstractContentPage Class Reference abstract
This class is an abstract base class for ContentPages for the Outlining for an ASMEditor.
Public Member Functions
AbstractContentPage (ITextEditor parentEditor, ITreeContentProvider contentProvider, IBaseLabelProvider labelProvider)
Genearates a new AbstractContentPage.
ITreeContentProvider getContentProvider ()
IBaseLabelProvider getLabelProvider ()
void createControl (Composite parent)
Creates a TreeViewer for visualizing this page and sets the content and label providers for the TreeViewer.
void setInput (Object input)
Sets a new input for the ContentPage and updates the TreeViewer.
void update (Observable o, Object arg)
This method is called after each run of the parser, as defined by the Observer interface.
void selectionChanged (SelectionChangedEvent event)
This method is called if the user clicks onto a node of the outline tree.
Protected Member Functions
void update ()
Updates and redraws the tree viewer.
abstract void setHighlighting (Object element)
This method must be implemented by subclasses to retrieve the information out of the given element.
Protected Attributes
ITextEditor parentEditor
Private Attributes
IEditorInput input
ITreeContentProvider contentProvider
IBaseLabelProvider labelProvider
Detailed Description
This class is an abstract base class for ContentPages for the Outlining for an ASMEditor.
Author
Markus Müller
Definition at line 26 of file AbstractContentPage.java.
Constructor & Destructor Documentation
org.coreasm.eclipse.editors.outlining.AbstractContentPage.AbstractContentPage (ITextEditor parentEditor, ITreeContentProvider contentProvider, IBaseLabelProvider labelProvider)
Genearates a new AbstractContentPage.
If the subclass doesn't provide a content provider or a label provider, a default implementation is created.
Definition at line 41 of file AbstractContentPage.java.
Member Function Documentation
void org.coreasm.eclipse.editors.outlining.AbstractContentPage.selectionChanged (SelectionChangedEvent event)
This method is called if the user clicks onto a node of the outline tree.
In this case, the editor should highlight the region which the clicked node refers to. This method retrieves the selected element from the tree and delegates it to the abstract method setHiglighting.
Definition at line 146 of file AbstractContentPage.java.
References org.coreasm.eclipse.editors.outlining.AbstractContentPage.setHighlighting().
abstract void org.coreasm.eclipse.editors.outlining.AbstractContentPage.setHighlighting (Object element) abstract protected
This method must be implemented by subclasses to retrieve the information out of the given element.
This element is typically one of the object which were provided by the content provider of the subclass.
Referenced by org.coreasm.eclipse.editors.outlining.AbstractContentPage.selectionChanged().
void org.coreasm.eclipse.editors.outlining.AbstractContentPage.setInput (Object input)
Sets a new input for the ContentPage and updates the TreeViewer.
Parameters
input The new input for the view.
Definition at line 95 of file AbstractContentPage.java.
References org.coreasm.eclipse.editors.outlining.AbstractContentPage.update().
void org.coreasm.eclipse.editors.outlining.AbstractContentPage.update (Observable o, Object arg)
This method is called after each run of the parser, as defined by the Observer interface.
It calls the update() method, so the outline view gets updated after each run of the parser.
Definition at line 127 of file AbstractContentPage.java.
References org.coreasm.eclipse.editors.outlining.AbstractContentPage.update().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/outlining/AbstractContentPage.java