Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.errors.ErrorManager Class Reference
org.coreasm.eclipse.editors.errors.ErrorManager Class Reference
An ErrorManager checks a CoreASM specification for errors beyond syntax errors.
Public Member Functions
ErrorManager (ASMEditor asmEditor)
Generates a new ErrorManager and adds all available ErrorRecognizers to itself.
void addErrorRecognizer (IErrorRecognizer errorRecognizer)
Adds an ErrorRegognizer to this ErrorManager, so the ErrorRecognizer will be run after each run of the parser.
void addWarningRecognizer (IWarningRecognizer warningRecognizer)
Adds a WarningRecognizer to this ErrorManager.
List< AbstractError > checkAllTextErrorRecognizers (ASMDocument document)
Executes all ErrorRecognizers implementing the ITextErrorRecognizer interface and collects the errors which were found in a list.
List< AbstractError > checkAllTreeErrorRecognizers (ASMDocument document)
Executes all ErrorRecognizers implementing the ITreeErrorRecognizer interface and collects the errors which were found in a list.
List< AbstractError > checkAllErrorRecognizer (ASMDocument document)
Executes all ErrorRecognizers (both TextErrorRecognizers and TreeErrorRecognizers) interface and collects the errors which were found in a list.
List< AbstractWarning > checkAllWarnings (ASMDocument document)
Execute all WarningRecognizers.
void update (Observable o, Object arg)
This is the method of the Observer interface which is called after each run of the parser.
Private Member Functions
int getErrorLength (String token, String strDoc, int index)
void deleteDuplicatesAndSortList (List< String > list)
Private Attributes
ASMEditor asmEditor
List< ITextErrorRecognizer > listTextParsers
List< ITreeErrorRecognizer > listTreeParsers
List< IWarningRecognizer > warningRecognizers
Detailed Description
An ErrorManager checks a CoreASM specification for errors beyond syntax errors.
Each instance of ASMEditor creates an ErrorManager and binds it to its ASMParser as an Observer. So the ErrorManager gets notified each time the parser was run.
An ErrorManager manages a list of objects implementing the IErrorRecognizer interface. These objects are doing the actual error checking, each error recognizer searches for a certain kind of errors. The ErrorManager executes these ErrorRegognizers after each run of the parser.
Author
Markus Müller
Definition at line 36 of file ErrorManager.java.
Constructor & Destructor Documentation
org.coreasm.eclipse.editors.errors.ErrorManager.ErrorManager (ASMEditor asmEditor)
Generates a new ErrorManager and adds all available ErrorRecognizers to itself.
Parameters
asmEditor The ASMEditor instance the generated ErrorManager belongs to.
Definition at line 47 of file ErrorManager.java.
References org.coreasm.eclipse.editors.errors.ErrorManager.addErrorRecognizer(), org.coreasm.eclipse.editors.errors.ErrorManager.addWarningRecognizer(), and org.coreasm.eclipse.editors.ASMEditor.getParser().
Member Function Documentation
void org.coreasm.eclipse.editors.errors.ErrorManager.addWarningRecognizer (IWarningRecognizer warningRecognizer)
Adds a WarningRecognizer to this ErrorManager.
Parameters
warningRecognizer
Definition at line 82 of file ErrorManager.java.
Referenced by org.coreasm.eclipse.editors.errors.ErrorManager.ErrorManager().
List<AbstractError> org.coreasm.eclipse.editors.errors.ErrorManager.checkAllErrorRecognizer (ASMDocument document)
Executes all ErrorRecognizers (both TextErrorRecognizers and TreeErrorRecognizers) interface and collects the errors which were found in a list.
Parameters
document The document which is to be checked.
Returns
A list with all errors which have been found.
See Also
org.coreasm.eclipse.editors.errors.ITextErrorRecognizer
org.coreasm.eclipse.editors.errors.ITreeErrorRecognizer
Definition at line 124 of file ErrorManager.java.
References org.coreasm.eclipse.editors.errors.ErrorManager.checkAllTextErrorRecognizers(), and org.coreasm.eclipse.editors.errors.ErrorManager.checkAllTreeErrorRecognizers().
List<AbstractError> org.coreasm.eclipse.editors.errors.ErrorManager.checkAllTextErrorRecognizers (ASMDocument document)
Executes all ErrorRecognizers implementing the ITextErrorRecognizer interface and collects the errors which were found in a list.
Parameters
document The document which is to be checked.
Returns
A list with all errors which have been found.
See Also
org.coreasm.eclipse.editors.errors.ITextErrorRecognizer
Definition at line 93 of file ErrorManager.java.
Referenced by org.coreasm.eclipse.editors.errors.ErrorManager.checkAllErrorRecognizer(), and org.coreasm.eclipse.editors.errors.ErrorManager.update().
List<AbstractError> org.coreasm.eclipse.editors.errors.ErrorManager.checkAllTreeErrorRecognizers (ASMDocument document)
Executes all ErrorRecognizers implementing the ITreeErrorRecognizer interface and collects the errors which were found in a list.
Parameters
document The document which is to be checked.
Returns
A list with all errors which have been found.
See Also
org.coreasm.eclipse.editors.errors.ITreeErrorRecognizer
Definition at line 108 of file ErrorManager.java.
Referenced by org.coreasm.eclipse.editors.errors.ErrorManager.checkAllErrorRecognizer(), and org.coreasm.eclipse.editors.errors.ErrorManager.update().
List<AbstractWarning> org.coreasm.eclipse.editors.errors.ErrorManager.checkAllWarnings (ASMDocument document)
Execute all WarningRecognizers.
Parameters
document document to be checked
Returns
list of warnings that have been found
Definition at line 137 of file ErrorManager.java.
Referenced by org.coreasm.eclipse.editors.errors.ErrorManager.update().
void org.coreasm.eclipse.editors.errors.ErrorManager.update (Observable o, Object arg)
This is the method of the Observer interface which is called after each run of the parser.
It executes the ErrorRecognizers depending if the parsing was successful and creates an error marker for each error. It also creates a marker if the parser delivered a syntax error or an unknown error.
Parameters
o The observable which has called this method. This must be the parser instance which is bound to the same instance of ASMEditor than this ErrorManager.
arg The data the Observable delivered. This must be an instance of ParsingResult.
Definition at line 156 of file ErrorManager.java.
References org.coreasm.eclipse.editors.errors.ErrorManager.checkAllTextErrorRecognizers(), org.coreasm.eclipse.editors.errors.ErrorManager.checkAllTreeErrorRecognizers(), org.coreasm.eclipse.editors.errors.ErrorManager.checkAllWarnings(), and org.coreasm.eclipse.editors.ASMEditor.getParser().
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/errors/ErrorManager.java