Eclipse_Plugin_for_CoreASM: org.coreasm.eclipse.editors.contentassist.TemplateManager Class Reference
org.coreasm.eclipse.editors.contentassist.TemplateManager Class Reference
Public Member Functions
TemplateStore getTemplateStore ()
Returns this plug-in's template store.
ContextTypeRegistry getContextTypeRegistry ()
Returns this plug-in's context type registry.
ImageRegistry getImageRegistry ()
IPreferenceStore getPreferenceStore ()
void savePluginPreferences ()
Static Public Member Functions
static TemplateManager getInstance ()
static ImageDescriptor imageDescriptorFromPlugin (String string, String default_image)
Private Attributes
TemplateStore fStore
The template store.
ContributionContextTypeRegistry fRegistry
The context type registry.
Static Private Attributes
static final String CUSTOM_TEMPLATES_KEY
Key to store custom templates.
static TemplateManager instance
The shared instance.
Detailed Description
Author
Tobias
Singleton manager for templates
Definition at line 20 of file TemplateManager.java.
Member Function Documentation
ContextTypeRegistry org.coreasm.eclipse.editors.contentassist.TemplateManager.getContextTypeRegistry ()
Returns this plug-in's context type registry.
Returns
the context type registry for this plug-in instance
Definition at line 71 of file TemplateManager.java.
References org.coreasm.eclipse.editors.contentassist.TemplateManager.fRegistry.
Referenced by org.coreasm.eclipse.editors.contentassist.TemplateManager.getTemplateStore().
TemplateStore org.coreasm.eclipse.editors.contentassist.TemplateManager.getTemplateStore ()
Returns this plug-in's template store.
Returns
the template store of this plug-in instance
Definition at line 51 of file TemplateManager.java.
References org.coreasm.eclipse.editors.contentassist.TemplateManager.CUSTOM_TEMPLATES_KEY, org.coreasm.eclipse.editors.contentassist.TemplateManager.fStore, org.coreasm.eclipse.editors.contentassist.TemplateManager.getContextTypeRegistry(), and org.coreasm.eclipse.CoreASMPlugin.getDefault().
Member Data Documentation
final String org.coreasm.eclipse.editors.contentassist.TemplateManager.CUSTOM_TEMPLATES_KEY static private
Initial value:
= CoreASMPlugin.getDefault()
            .toString() + ".customtemplates"
Key to store custom templates.
Definition at line 22 of file TemplateManager.java.
Referenced by org.coreasm.eclipse.editors.contentassist.TemplateManager.getTemplateStore().
ContributionContextTypeRegistry org.coreasm.eclipse.editors.contentassist.TemplateManager.fRegistry private
The context type registry.
Definition at line 32 of file TemplateManager.java.
Referenced by org.coreasm.eclipse.editors.contentassist.TemplateManager.getContextTypeRegistry().
TemplateStore org.coreasm.eclipse.editors.contentassist.TemplateManager.fStore private
The template store.
Definition at line 29 of file TemplateManager.java.
Referenced by org.coreasm.eclipse.editors.contentassist.TemplateManager.getTemplateStore().
TemplateManager org.coreasm.eclipse.editors.contentassist.TemplateManager.instance static private
The shared instance.
Definition at line 26 of file TemplateManager.java.
The documentation for this class was generated from the following file:
src/org/coreasm/eclipse/editors/contentassist/TemplateManager.java